# Generated by Django 5.2.16 on 2026-08-03 11:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodCategory',
            fields=[
                ('code', models.CharField(max_length=32, primary_key=True, serialize=False, verbose_name='分类编码')),
                ('name', models.CharField(max_length=64, verbose_name='类目名称')),
                ('level', models.IntegerField(choices=[(1, '一级类目'), (2, '二级类目'), (3, '三级类目')], verbose_name='层级')),
                ('parent_code', models.CharField(blank=True, max_length=32, null=True, verbose_name='父级编码')),
            ],
            options={
                'verbose_name': '食品类目',
                'verbose_name_plural': '食品类目',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='SiteConfig',
            fields=[
                ('key', models.CharField(max_length=32, primary_key=True, serialize=False, verbose_name='配置键')),
                ('value', models.CharField(max_length=64, verbose_name='配置值')),
            ],
            options={
                'verbose_name': '站点配置',
                'verbose_name_plural': '站点配置',
            },
        ),
        migrations.CreateModel(
            name='FoodSample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='食品名称')),
                ('description', models.TextField(blank=True, verbose_name='品类描述')),
                ('source', models.CharField(choices=[('seed', '内置种子数据'), ('user', '用户上传')], default='seed', max_length=16, verbose_name='数据来源')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classifier.foodcategory', verbose_name='所属三级类目')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
            options={
                'verbose_name': '食品样本',
                'verbose_name_plural': '食品样本',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OperationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=64, verbose_name='操作类型')),
                ('detail', models.TextField(blank=True, verbose_name='操作详情')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='时间')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='操作人')),
            ],
            options={
                'verbose_name': '操作日志',
                'verbose_name_plural': '操作日志',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PredictionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_text', models.TextField(verbose_name='输入文本')),
                ('predicted_code', models.CharField(max_length=32, verbose_name='预测类目编码')),
                ('predicted_name', models.CharField(max_length=64, verbose_name='预测类目名称')),
                ('confidence', models.FloatField(verbose_name='置信度')),
                ('model_name', models.CharField(max_length=32, verbose_name='使用模型')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='推理时间')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='操作人')),
            ],
            options={
                'verbose_name': '分类推理记录',
                'verbose_name_plural': '分类推理记录',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('student', '实训学生'), ('admin', '后台管理员')], default='student', max_length=16, verbose_name='角色')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '用户角色',
                'verbose_name_plural': '用户角色',
            },
        ),
    ]
